site: Andrew Gazelka
title: Andrew Gazelka
greetings: WELCOME 🦾
description: >-
  Read my blog for if you enjoy my opinions, ideas, and rants :)
lang: en-US
timezone: America/Los_Angeles
repo: https://github.com/andrewgazelka/andrewgazelka.github.io # site repo [optional]
data-theme: dark # default theme "dark" | "light"
# discus-identifier: powex # replace with your disqus shortname

author:
  name: Andrew Gazelka
  bio: just a minimalist, personal blog
  userpicture:
  username: # general username
  github: andrewgazelka
  twitter: # twitter username
  email: andrewgazelka@gmail.com # email adress

# Font Settings
googlewebfonts: family=Inter:wght@400;700&family=Fira+Code:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,300;1,400;1,500;1,600;1,700;1,900

# URL settings
url: "https://andrew.tech" # Domain Name of host. [username].github.io for github pages
# baseurl: "/Gesko" # sub folder for jekyll site. only if jekyll site not in root of host. leave blank if not wishd. always add / in front.
permalink: pretty

# local
# url: "http://localhost:4000" #
# baseurl: "" #

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links
  - jekyll-latex

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slug

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled: true
  collections: false
